# Generated by Django 2.2.9 on 2020-02-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', models.BooleanField()),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='jobfinder.Profile')),
                ('Employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='jobfinder.Profile')),
                ('Jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobfinder.Job')),
            ],
        ),
    ]
