# Generated by Django 2.2.9 on 2020-06-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0002_jobconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobconnection',
            name='Employer',
        ),
    ]
