# Generated by Django 2.2.9 on 2020-06-04 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0003_remove_jobconnection_employer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterModelOptions(
            name='skillset',
            options={'verbose_name': 'Skill Set', 'verbose_name_plural': 'Skill Sets'},
        ),
        migrations.AddField(
            model_name='job',
            name='Title',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
